---
- hosts: all
  name: Add cis-91 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip 
          - python3-venv
          - nginx

    - name: Create data directory
      file:
        path: /mnt/data
        state: directory


    - name: Create a ext4 filesystem for lab09
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-lab09

    - name: Mount extra disk
      ansible.posix.mount:
        path: /mnt
        src: /dev/disk/by-id/google-lab09
        fstype: ext4
        state: mounted   

    - name: Create a ext2 filesystem for blockstorage
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-blockstorage

    - name: Mount up blockstorage
      ansible.posix.mount:
        path: /mnt/data
        src: /dev/disk/by-id/google-blockstorage
        fstype: ext4
        state: mounted       