---
- hosts: all
  name: Add required software
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - php-xml

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Unarchive dokuwiki
      ansible.builtin.unarchive:
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        remote_src: yes
        mode: u+rwx,g+rwx,o+rwx

    - name: Create a ext4 filesystem
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-dokuwiki-data

    - name: Mount persistent disk
      ansible.posix.mount:
        path: /var/www
        src: /dev/disk/by-id/google-dokuwiki-data
        fstype: ext4
        state: mounted

    - name: Copy bucket backup executable
      ansible.builtin.copy:
        src: backup
        dest: /etc/cron.hourly/backup
        owner: root
        group: root
        mode: '0744'
        
